version: '3.9'

services:
  zipkin_svc:
    image: openzipkin/zipkin
    container_name: zipkin_svc
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    networks:
      - services_ntw

  otel_collector:
    image: otel/opentelemetry-collector:0.95.0
    container_name: otel_collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # gRPC port
      - "4318:4318" # HTTP port
    depends_on:
      - zipkin_svc
    networks:
      - services_ntw

  service_b:
    build:
      context: .
      dockerfile: Dockerfile-svc-b
    image: service_b
    container_name: service_b
    ports:
      - "50055"
    networks:
      - services_ntw
    depends_on:
      - otel_collector

  service_a:
    build:
      context: .
      dockerfile: Dockerfile-svc-a
    image: service_a
    container_name: service_a
    ports:
      - "8080:8080"
    networks:
      - services_ntw
    depends_on:
      - service_b

networks:
  services_ntw:
