# SERVICE B: Orchestration

FROM golang:1.22-bookworm as builder
WORKDIR /app
COPY . .
RUN make init && make service-b/build

FROM scratch
COPY --from=builder /app/server .
COPY --from=builder /app/env.json .
EXPOSE 50055
CMD ["./server"]
