# SERVICE B: Orchestration

FROM golang:1.22-bookworm as builder
WORKDIR /app
COPY . .
RUN curl -sL https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
RUN apt-get update && apt-get install -y protobuf-compiler
RUN make init && make service-b/build

FROM scratch
COPY --from=builder /app/server .
COPY --from=builder /app/env.json .
EXPOSE 50055
CMD ["./server"]
